# Generated by Django 4.1.3 on 2022-12-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('LV', '사랑'), ('MN', '금전'), ('FT', '진로')], max_length=2)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'answer_data',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
            ],
        ),
    ]
