# Generated by Django 4.1.3 on 2022-12-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=2)),
                ('question', models.CharField(max_length=50, null=True)),
                ('content', models.TextField()),
                ('create_date', models.DateField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=2)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'answer_data',
            },
        ),
    ]
