# Generated by Django 4.1.3 on 2022-12-09 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerFuture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'answer_future',
            },
        ),
        migrations.CreateModel(
            name='AnswerLove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'answer_love',
            },
        ),
        migrations.CreateModel(
            name='AnswerMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'answer_money',
            },
        ),
        migrations.CreateModel(
            name='QuestionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=2)),
                ('question', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AnswerData',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='subject',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door.questionform'),
        ),
    ]
