# Generated by Django 4.1.3 on 2022-12-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0002_answerfuture_answerlove_answermoney_questionform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionform',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
