# Generated by Django 4.1.3 on 2022-12-10 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0003_alter_questionform_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionForm',
            new_name='Question',
        ),
    ]
